# Generated by Django 5.2.17 on 2026-08-21 15:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=20)),
                ('target_currency', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))])),
                ('effective_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ('-effective_date', 'base_currency', 'target_currency'),
                'indexes': [models.Index(fields=['base_currency', 'target_currency', 'effective_date'], name='currencies__base_cu_4607f0_idx')],
            },
        ),
    ]
