# Generated by Django 5.2.17 on 2026-08-21 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.TextField(blank=True)),
                ('assigned_credit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='customers.customer')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credentials', to='providers.apiendpoint')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credentials', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Customer Credential',
                'verbose_name_plural': 'Customer Credentials',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'status'], name='customer_cr_provide_109442_idx'), models.Index(fields=['expire_date', 'status'], name='customer_cr_expire__6e0166_idx')],
            },
        ),
    ]
