# Generated by Django 5.2.17 on 2026-08-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_creditpurchase_valuation_snapshot'),
        ('customer_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredential',
            name='credit_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credentials', to='credits.customercreditallocation'),
        ),
    ]
