# Generated by Django 5.2.17 on 2026-08-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_credentials', '0002_customercredential_credit_allocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercredential',
            options={'ordering': ('-created_at',), 'permissions': (('view_sensitive_api_key', 'Can view decrypted API keys'),), 'verbose_name': 'Customer Credential', 'verbose_name_plural': 'Customer Credentials'},
        ),
    ]
