# Generated by Django 5.2.17 on 2026-08-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_credentials', '0004_alter_customercredential_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercredential',
            name='assigned_credit_usd',
        ),
        migrations.RemoveField(
            model_name='customercredential',
            name='cost_price_usd',
        ),
        migrations.RemoveField(
            model_name='customercredential',
            name='selling_price_usd',
        ),
    ]
