# Generated by Django 5.2.17 on 2026-08-21 14:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('credit_amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('paid_currency', models.CharField(db_index=True, max_length=20)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_purchases', to='providers.apiendpoint')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='providers.provider')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Credit Purchase',
                'verbose_name_plural': 'Credit Purchases',
                'ordering': ('-purchase_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_credit_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('used_credit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_credit_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='credits.creditpurchase')),
            ],
            options={
                'verbose_name': 'Credit Balance',
                'verbose_name_plural': 'Credit Balances',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['provider', 'status'], name='credits_cre_provide_332312_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['wallet', 'purchase_date'], name='credits_cre_wallet__5ac812_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount_usd__gt', 0)), name='credit_purchase_credit_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gt', 0)), name='credit_purchase_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='credit_purchase_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditbalance',
            constraint=models.CheckConstraint(condition=models.Q(('used_credit_usd__gte', 0)), name='credit_balance_used_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditbalance',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_credit_usd__gte', 0)), name='credit_balance_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditbalance',
            constraint=models.CheckConstraint(condition=models.Q(('used_credit_usd__lte', models.F('total_credit_usd'))), name='credit_balance_used_lte_total'),
        ),
    ]
