# Generated by Django 5.2.17 on 2026-08-21 14:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_credit_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_credit_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('credit_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_allocations', to='credits.creditpurchase')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='customers.customer')),
                ('provider', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_allocations', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Customer Credit Allocation',
                'verbose_name_plural': 'Customer Credit Allocations',
                'ordering': ('-start_date', '-created_at'),
                'indexes': [models.Index(fields=['customer', 'status'], name='credits_cus_custome_59df8a_idx'), models.Index(fields=['credit_purchase', 'status'], name='credits_cus_credit__9fb99e_idx'), models.Index(fields=['provider', 'expire_date'], name='credits_cus_provide_d731cb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('allocated_credit_usd__gt', 0)), name='allocation_credit_positive'), models.CheckConstraint(condition=models.Q(('cost_price_usd__gte', 0)), name='allocation_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('selling_price_usd__gte', 0)), name='allocation_selling_nonnegative'), models.CheckConstraint(condition=models.Q(('remaining_credit_usd__gte', 0)), name='allocation_remaining_nonnegative'), models.CheckConstraint(condition=models.Q(('remaining_credit_usd__lte', models.F('allocated_credit_usd'))), name='allocation_remaining_lte_allocated')],
            },
        ),
    ]
