# Generated by Django 5.2.17 on 2026-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
