# Generated by Django 5.2.17 on 2026-08-21 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0002_customercreditallocation'),
        ('customers', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('EXPENSE', 'Expense'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], db_index=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('currency', models.CharField(db_index=True, max_length=20)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateField(db_index=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credits.customercreditallocation')),
                ('credit_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='credits.creditpurchase')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-transaction_date', '-created_at'),
                'indexes': [models.Index(fields=['transaction_type', 'transaction_date'], name='transaction_transac_ced4d1_idx'), models.Index(fields=['customer', 'transaction_date'], name='transaction_custome_f6072d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0), ('exchange_rate__isnull', True), _connector='OR'), name='transaction_exchange_rate_positive')],
            },
        ),
    ]
