# Generated by Django 5.2.17 on 2026-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(db_index=True, max_length=20)),
                ('network', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['currency', 'network', 'is_active'], name='wallets_wal_currenc_8bcacf_idx')],
            },
        ),
    ]
